#!/usr/bin/python3
# COMP3311 20T3 Ass3 ... print name, year, ratings of top N movies

import sys
import psycopg2

# globals

usage = "Usage: best [N]"

bestQ = """
select rating, title, start_year
from Movies 
order by rating desc, title limit %s;
"""

db = None

# process command-line args

argc = len(sys.argv)
if argc > 2:
	print(usage)
	exit(1)
else:
	if (argc == 1):
		N = 10
	else:
		N = sys.argv[1]
		try:
			if (int(N) < 1):
				print("Usage: best [N]")
				exit(1)
		except ValueError:
				print(usage)
				exit(1)
	
# manipulate database

try:
	db = psycopg2.connect("dbname=imdb")
	cur = db.cursor()
	cur.execute(bestQ, [N])
	movies = cur.fetchall()
	for tup in movies:
		rating, title, year = tup
		print(f"{rating} {title} ({year})")
		
except psycopg2.Error as err:
	print("DB error: ", err)
finally:
	if db:
		db.close()

